#!/bin/sh
### BEGIN INIT INFO
# Provides:          thermosmart-zwave
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Should-Start:      mosquitto
# Should-Stop:       mosquitto
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ThermoSmart Z-Wave MQTT
# Description:       Node.JS Z-Wave gateway to control devices over MQTT
### END INIT INFO

# Author: Alexandre Thomazo <alex@thomazo.info>

PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin
DESC="thermosmart-zwave"
NAME=thermosmart-zwave
DAEMON=/usr/local/bin/node
DAEMON_PATH="/opt/thermosmart/thermosmart-zwave"
USER=pi
GROUP=pi
LOGFILE=$DAEMON_PATH/$NAME.log
PIDFILE=$DAEMON_PATH/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

NODEAPP_DIR=$DAEMON_PATH
NODEAPP_SCRIPT="index.js"

[ -x "$DAEMON" ] || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start()
{
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1

	start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE \
		--exec $DAEMON --chdir $NODEAPP_DIR --chuid $USER:$GROUP \
		--background -- $NODEAPP_SCRIPT >> $LOGFILE 2>&1 || return 2
}

do_stop()
{
        start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
        RETVAL="$?"
        [ "$RETVAL" = 2 ] && return 2

        start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --pidfile $PIDFILE
        [ "$?" = 2 ] && return 2

        rm -f $PIDFILE
        return "$RETVAL"
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc -p $PIDFILE "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;;
			*) log_end_msg 1 ;;
		esac
		;;
	  *)
		log_end_msg 1
		;;
	esac
	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
